name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v4

    - name: Defini versão do node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install
    
    - name: Executar Testes unitários
      run: npm run teste-unitario

    - name: Executar Testes de integração
      run: npm run teste-integracao

  implantar:
      needs: [testar]
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20.x]

      script:
        git fetch
        git checkout main
        git pull
        cd ~/projeto-ci-cd-pos-puc
        npm i
        npm run start

    
